; Project Euler Problem #29

; Problem #29 text:
; Consider all integer combinations of a^b for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
; 2^2=4, 2^3=8, 2^4=16, 2^5=32
; 3^2=9, 3^3=27, 3^4=81, 3^5=243
; 4^2=16, 4^3=64, 4^4=256, 4^5=1024
; 5^2=25, 5^3=125, 5^4=625, 5^5=3125
; If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
; 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
; How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

; code
#SingleInstance

; AHK doesn't have arbitrary-precision numbers, and I don't want to compare and generate 200-digit numbers, so I'll do this manually:
; a and b have a range of 99, so the maximum number of a^b combinations is 99^99 = 9801
; now to remove duplicates:

; quadratic:
; 4^2, 4^3, 4^4, ... 4^50 = 2^4, 2^6, 2^8, ... 2^50
; numbers in this category: 4, 9, 25, 36, 49, 100
; 6 numbers * 49 duplicate powers → 294 duplicates

; cubic:
; 8^2, 8^3, 8^4, ... 8^33 = 2^6, 2^9, 2^12, ... 2^99
; 8^34, 8^36, 8^38, ... 8^50 = 4^51, 4^54, 4^57, ... 4^50
; numbers in this category: 8, 27
; 2 numbers * (32 + 17) duplicate powers → 98 duplicates

; quartic:
; 16^2, 16^3, 16^4, ... 16^50 = 4^4, 4^6, 4^8, ... 4^100
; 16^51, 16^54, 16^57, ... 16^75 = 8^68, 8^72, 8^76, ... 8^100
; numbers in this category: 16, 81
; 2 numbers * (49 + 9) duplicate powers → 116 duplicates

; quintic:
; 32^2, 32^3, 32^4, ... 32^20 = 2^10, 2^15, 2^20, ... 2^100
; 32^22, 32^24, 32^26, ... 32^40 = 4^55, 4^60, 4^65, ... 4^100
; 32^42, 32^45, 32^48, ... 32^60 = 8^70, 8^75, 8^80, ... 8^100
; + 32^21, 32^27, 32^33, 32^39 = 8^35, 8^45, 8^55, 8^65 (skip the case where the exponent is a multiple of 2, since 32^24 = 8^40 = 4^60 was already covered)
; 32^64, 32^68, 32^72, 32^76, 32^80 = 16^80, 16^85, 16^90, 16^95, 16^100
; + 32^44, 32^52, 32^56 = 16^85, 16^90, 16^95, 16^100 (skip the case where the exponent is a multiple of 3, since 32^48 = 16^60 = 8^80 was already covered)
; number in this category: 32
; 1 number * (19 + 10 + (7+4) + (5+3)) duplicate powers → 48 duplicates

; sextic:
; 64^2, 64^3, 64^4, ... 64^50 = 8^4, 8^6, 8^8, ... 8^100
; 64^52, 64^54, 64^56, ... 64^66 = 16^78, 16^81, 16^84, ... 16^99
; 64^70, 64^75, 64^80 = 32^84, 32^90, 32^96
; + 64^55, 64^65 = 32^66, 32^78 (skip the case where the exponent is a multiple of 2, since 64^60 = 32^72 = 16^90 was already covered)
; number in this category: 64
; 1 number * (49 + 8 + (3+2)) duplciate powers → 62 duplicates

; septic:
; no need to check; 2^7 = 128 would be the first, and 128 > 100

; subtract all the duplicates from the maximum total
answer := 99**2 - (294 + 98 + 116 + 48 + 62)

msgbox, %answer%
Clipboard := answer

ExitApp